### ISSUE TITLE
Using the same nodes (example: A -> B) twice overrides the first one

### ISSUE THREAD

**Issue by LuisDavidR** [hrgruri/dijkstra#1]
Hi, first of all,great library, very simple to use!

But I have a question, I added two nodes with the same points and the first one gets override by the second.

A->B, cost 5
A->B, cost 10

This library doesn't keep both options, it just discard the first combination (A->B, cost 5).
Is there a way to change this? I need both options.

Thanks in advance,
Luís Rodrigues

**Comment by taniko** [comment]
Thank you for using.

If there are multiple links between the same nodes, it is obvious that the shorter link will be chosen. So this library keep only one link.

You can keep multiple links by adding meaningless nodes.
A->B (cost: 5)
A->temp->B (cost: 0, 10)

**Comment by LuisDavidR** [comment]
Hi, thanks for your quick response.

My problem is that the overridden nodes aren't the longest but the first.

For example, if I add this two nodes by this order:
A -> B cost 5
A -> B cost 10

It will choose the last one, which is longer than the first.

Best regards,
Luís Rodrigues

A Qua, 11 de abr de 2018, 04:59, Yuya Aratani <notifications@github.com>
escreveu:

**Comment by LuisDavidR** [comment]
Hi,
sorry for the trouble. I think my question has nothing to do with the library itself but maybe you can help me.

I tried to catch the throw new \UnexpectedValueException, but it just doesn't recognize the Exception object. Do you have any clue why that happens? My PHP version is 7.2.3.

I even tried to change the type of the exception, but with no success...

**Because when I choose 2 nodes that are not connected, i.e., there is no route that can connect both nodes, it should throw me an exception, but instead just gives me an error because it doesnt recognize the object Exception. So I can't handle the exception .**

Thanks,
Luis Rodrigues

**Comment by taniko** [comment]
I'm sorry. I forgot to add new tag after changing namespace.
Could you update installed library version. Please use >=1.1.0.

Do you catching `\UnexpectedValueException`? 
If you use inside a namespace, you have to catch `\UnexpectedValueException`. Not `UnexpectedValueException`.
I sometimes missing `\` and could not catch Exception.
Could you check your code, please.

```php
<?php
namespace Foo\Bar;

require __DIR__ . '/vendor/autoload.php';

$graph = \Taniko\Dijkstra\Graph::create();

$graph->add('a', 'b', 1)->add('c', 'd', 1);

try {
    $graph->search('a', 'c');
} catch (UnexpectedValueException $e) {
    print 'not called';
} catch (\UnexpectedValueException $e) {
    print 'called';
};

```

**Comment by LuisDavidR** [comment]
Thanks again for your quick response. I understood the importance of the `\` thanks :)

But the problem is that i'm not using any framework and I don't know how to use composer and autoload, I'm just coding in notepad++.

Do you know if there is a way to use the Exceptions, with try and catch without installing anything?

Best regards,
Luís Rodrigues

**Comment by taniko** [comment]
If you use like this, you can change exception type and catch any exception.

```php
<?php
require __DIR__ . '/Graph.php';

$graph = Taniko\Dijkstra\Graph::create();
try {
    try {
        $graph->search('a', 'b');
    } catch (UnexpectedValueException $e) {
        print "called\n";
        print get_class($e) . "\n"; // UnexpectedValueException
        throw new Exception;
    }
} catch (Throwable $e) {
    print get_class($e) . "\n"; // Exception
}
```
